apiVersion: v1
kind: Namespace
metadata:
  name: givemejobs-production
  labels:
    name: givemejobs-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: givemejobs-staging
  labels:
    name: givemejobs-staging
    environment: staging
